services:
  - type: web
    name: puentes-globales-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        value: 10000
